import hashlib
import os
import json

translate_total = {}
translate_file_path = r'C:\Users\WIN10\Desktop\python\ScrapyDemo\ufcjson/ufc_translat.json'

if os.path.exists(translate_file_path):
   with open(translate_file_path, 'r', encoding="utf-8") as file:
       translate_total = json.load(file)

#检验是否含有中文字符
# def is_contains_chinese(strs):
#     for _char in strs:
#         if '\u4e00' <= _char <= '\u9fa5':
#             return True
#     return False

# for key in translate_total.keys():
#     if not is_contains_chinese(translate_total[key]):
#         print(translate_total[key])


not_tr={"da'mon blackshear":"达蒙-布莱克希尔",
"Tabatha Ricci":"塔巴莎·里奇",
"Vivianearaújo":"薇薇安娜拉乌若",
"Estebanribovics":"埃斯特万利博维奇",
"Valentina Shevchenko":"瓦莲京娜·舍甫琴科",
"Loik Radzhabov":"洛伊克·拉扎博夫",
"manamartinez":"马纳马丁内斯",
"Alexa Grasso":"亚历克莎·格拉索",
"Jalinturner":"贾林特纳",
"Trevinjones":"特雷维琼斯",
"ciryl gane":"西里尔·盖恩",
"Bonickal":"博尼克尔",
"mateuszgamrot":"马特乌斯加姆罗",
"Drikus Duplessis":"得力克斯-杜-普莱西斯",
"Ianmachadogarry":"伊恩马查多加里",
"Erin Blanchfield":"艾琳布兰奇菲尔德",
"Zac Pauga":"扎克保加",
"jamalpogues":"贾马尔波格斯",
"Mayrabuenosilva":"迈拉布埃诺席尔瓦",
"Linalansberg":"利纳兰斯伯格",
"Khusein Askhabov":"胡赛因·阿斯哈博夫",
"Jamallemmmers":"贾莫尔·埃默斯",
"Ovincesaintpreux":"省圣普雷",
"themba gorimbo":"金银花",
"ajfletcher":"阿杰弗莱彻",
"Juancamilo Ronderos":"胡安卡米洛·朗德罗斯",
"Serghei Spivac":"谢尔盖•斯皮瓦茨",
"Nassourdineimavov":"纳苏尔丁内马沃夫",
"Seanstrickland":"肖恩斯特里克兰",
"Devinclark":"德文克拉克",
"Dawoonjung":"多云中",
"Blagoy Ivanov":"布拉戈伊万诺夫",
"Kylenelson":"凯尼尔森",
"Doohochoi":"斗湖菜",
"Yusaku Kinoshita":"木下佑作",
"Damonjackson":"达蒙杰克逊",
"Danige":"达尼格",
"Punahele Soriano":"普纳赫莱索里亚诺",
"Ketlen Vieira":"凯特伦维埃拉",
"Umar Nurmagomedov":"奥马尔·努尔马戈梅多夫",
"Andremuniz":"安德烈穆尼兹",
"Jared Cannonier":"贾里德坎农尼尔",
"Anshul Jubli":"安舒尔朱布里",
"Jeka Saragih":"杰卡萨拉吉",
"yizha":"益扎",
"Rinyanakamura":"林屋中村",
"Toshiomi Kazama":"风间敏臣",
"Hyunsungpark":"朴贤星",
"Seunggukchoi":"升国彩",
"Mateusmendonça":"马特乌门东萨",
"Javid Basharat":"贾维德·巴沙拉特",
"Abdulrazakalhassan":"阿卜杜拉扎卡哈桑",
"Claudioribeiro":"克劳迪奥里贝罗",
"MateuszręBecki":"马特乌斯雷贝基",
"Allan Nascimento":"艾伦·纳西门托",
"Dotale Mayes":"多塔莱·梅耶斯",
"Yohanlainesse":"约翰莱斯",
"Mikemalott":"麦克马洛特",
"Trevorpeek":"特雷弗皮克",
"Erickgonzalez":"埃里克冈萨雷斯",
"Yair Rodriguez":"耶尔·罗德里格斯",
"Jackdellamaddalena":"杰克德拉马达莱娜",
"Parkerporter":"帕克波特",
"Justintafa":"贾斯廷塔法",
"Alonzo Menifield":"阿朗佐梅尼菲尔德",
"Arman Tsarukyan":"阿尔曼察鲁金",
"Alessandrocosta":"亚历山德罗科斯塔",
"Alex Caceres":"亚历克斯·卡塞雷斯",
"Glover Teixeira":"格洛弗·特谢拉",
"Denis Tiuliulin":"丹尼斯·图柳林",
"Junyongpark":"俊永公园",
"Tatsuro Taira":"平达郎",
"Nickaguirre":"尼克吉雷",
"Danargueta":"达纳格塔",
"Jimmyflick":"吉米弗利克",
"Strickland vs Imavov":"斯特里克兰 VS 伊马沃夫",
"Jasminejasudavicius":"茉莉花",
"Victormartinez":"维克托马丁内斯",
"Modestas Bukauskas":"莫德斯塔斯·布考斯卡斯",
"Melsikbaghdasaryan":"梅尔西克巴格达萨良",
"Shannonross":"香农罗斯",
"Michaloleksiejczuk":"米迦勒克谢祖克",
"codybrundage":"科迪布伦戴奇",
"Cheyanne Vlismas":"夏安·维利斯玛斯",
"Matthew Semelsberger":"马修·塞默斯伯格",
"Jakematthews":"杰克马修斯",
"Saidyokub Kakhramonov":"赛尤库布•卡赫拉莫诺夫",
"Saidnurmagomedov":"赛德努尔马戈梅多夫",
"Deiveon Figueiredo":"戴维翁·菲格雷多",
"Laurenmurphy":"劳伦墨菲",
"Nurullo Aleie":"努鲁洛阿莱耶",
"Muniz vs Allen":"穆尼兹 vs 艾伦",
"Donshainis":"东赛尼斯",
"Elisereed":"埃莉斯里德",
"Loma Lookboonmee":"洛玛-洛克布恩梅",
"Blakebilder":"布莱克比尔德",
"Shaneyoung":"尚扬",
"Elvesbrener":"精灵布雷纳",
"Zubaira Tukhugov":"祖拜拉·图胡戈夫",
"Maheshate":"马赫沙特",
"Rafagarcia":"拉法加西亚",
"Rinatfakhretdinov":"里纳特法赫雷季诺夫",
"Bryanbattle":"布莱恩之战",
"MANEL KAPE":"马内尔卡佩",
"ihor Potieria":"伊霍尔·波蒂利亚",
"thiagomoises":"thiagomoises",
"Mounir Lazzez":"蒂亚戈·莫伊塞斯",
"Makhachev vs Volkanovski":"马哈切夫 VS 沃尔卡诺夫斯基",
"Cannonier vs Strickland":"坎农尼尔 vs 斯特里克兰",
"Shamilabdurakhimov":"沙米拉布杜拉希莫夫",
"Luan Lacerda":"卢安·拉塞尔达",
"Terrance McKinney":"特伦斯麦金尼",
"Ismael Bonfim":"伊斯梅尔邦芬",
"Zarahfairn":"扎拉费尔恩",
"Josiane Nunes":"约西亚娜努内斯",
"Danielmarcos":"丹尼尔马科斯",
"Teixeira vs Hill":"特谢拉 VS 希尔",
"Cory Sandhagen":"科里·桑德哈根",
"Yana Santos":"亚娜桑托斯",
"Nate Landwehr":"内特·兰德维尔",
"Alex Caceres":"亚历克斯·卡塞雷斯",
"Maycee Barber":"梅西理发师",
"Chidi Njokuani":"奇迪·纽库阿尼",
"Billy Quartillo":"比利·夸蒂罗",
"Azamatmurzakanov":"阿扎马特穆尔扎卡诺夫",
"Merab Dvalishvili":"梅拉布德瓦利什维利",
"Beneil dariush":"贝尼尔大流士",
"Sergei Pavlovich":"谢尔盖·帕夫洛维奇",
"Trevin Giles":"特雷文吉尔斯",
"Tanner Boser":"坦纳波瑟",
"Kron Gracie":"克朗格雷西",
"Danieldasilva":"丹尼尔达席尔瓦",
"CJ Vergara":"CJ维加拉",
"TJ Brown":"TJ布朗",
"Bill Algeo":"比尔阿尔吉奥",
"Virna Jandiroba":"维尔纳詹迪罗巴",
"Gunnar Nelson":"冈纳尼尔森",
"liang na":"梁娜",
"Zak Cummings":"扎克卡明斯",
"Chriscurtis":"克里斯柯蒂斯",
"Kelvin Gastelum":"开尔文加斯特鲁姆",
"Vinicius Salvador":"维尼修斯萨尔瓦多",
"Victor Altamirano":"维克托阿尔塔米拉诺",
"Clayguida":"克莱吉达",
"Vitor Petrino":"维托·佩特里诺",
"Armen Petrosyan":"亚门彼得相",
"Lukasz Brzeski":"卢卡斯布热斯基",
"Luana Pinheiro":"卢安娜·皮涅罗",
"Zhalgas Zhumagulov":"扎尔加斯朱马古洛夫",
"Makwan Amirkhani":"马克万·阿米尔哈尼",
"Matheus Nicolau":"马修斯·尼古劳",
"Raphaelassunção":"拉斐拉松桑",
"Rolando Bedoya":"罗兰多·贝多亚",
"Khaos Williams":"考斯·威廉姆斯",
"Yanal Ashmoz":"亚纳尔·阿什莫兹",
"Bruna Brasil":"布鲁纳巴西",
"Sedriques Dumas":"塞德里克斯·杜马斯",
"Jafel Filho":"杰菲尔菲尔霍",
"Guido Cannetti":"圭多·坎内蒂",
"Loopy Godinez":"疯疯癫癫的戈迪内斯",
"Duškotodorović":"杜斯科托多罗维奇",
"Lando Vannata":"兰多瓦纳塔",
"JJ Aldrich":"JJ奥尔德里奇",
"Ariane Lipski":"阿丽亚娜·利普斯基",
"Ignacio Bahamondes":"伊格纳西奥·巴哈蒙德斯",
"Shayilan Nuerdanbieke":"沙依兰努尔丹别克",
"samhughes":"桑休斯",
"Jaqueline Amorim":"杰奎琳·阿莫林",
"Ludovit Klein":"卢多维·克莱因",
"Abubakar Nurmagomedov":"阿布巴卡尔•努尔马戈梅多夫",
"Veronica Macedo":"维罗尼卡马塞多",
"Asjabharan _":"阿查巴兰_",
"angga-":"安哥拉-",
"Nariman Abbassov":"纳里曼·阿巴索夫",
"Hamdy Abdelwahab":"汉迪·阿卜杜勒瓦哈卜",
"Shamil Abdurakhimov":"沙米尔·阿卜杜拉希莫夫",
"Papy Abedi":"帕皮·阿贝迪",
"Cat Zingano":"猫津加诺",
"Deiveon Figueiredo":"戴维翁·菲格雷多",
"Kai Kara-France":"凯卡拉-法国",
"MANEL KAPE":"马内尔卡佩",
"Sumudaerji":"苏木达尔吉",
"Umar Nurmagomedov":"奥马尔·努尔马戈梅多夫",
"Yair Rodriguez":"耶尔·罗德里格斯",
"Brian Ortega":"布赖恩奥尔特加",
"Chan Sung Jung":"陈成正",
"Giga Chikadze":"千兆奇卡兹",
"Ilia topuria":"伊利亚",
"Movsar Evloev":"莫夫萨尔叶夫洛耶夫",
"Sodiq Yusuff":"索迪克尤瑟夫",
"Mateusz Gamrot":"马特乌斯·加姆罗",
"Arman Tsarukyan":"阿尔曼察鲁金",
"Renato Moicano":"雷纳托·莫卡诺",
"Khamzat Chimaev":"坎扎特奇马耶夫",
"Belal Muhammad":"贝拉穆罕默德",
"Shavkat Rakhmonov":"沙夫卡特•拉赫莫诺夫",
"Jared Cannonier":"贾里德坎农尼尔",
"Paulo Costa":"保罗科斯塔",
"Dricus du Plessis":"德里库斯·杜·普莱西斯",
"Nassourdine Imavov":"娜苏丁·伊马沃夫",
"JanBłachowicz":"扬布拉乔维茨",
"AleksandarRakić":"亚历山大·拉基奇",
"Volkan Oezdemir":"沃尔坎厄兹德米尔",
"Azamat Murzakanov":"阿扎马特·穆尔扎卡诺夫",
"ciryl gane":"西里尔·盖恩",
"stipe miocic":"斯蒂普·米欧奇",
"Serghei Spivac":"谢尔盖•斯皮瓦克",
"Jairzinho Rozenstruik":"雅伊尔津霍·罗森斯特鲁克",
"Blagoy Ivanov":"布拉戈伊万诺夫",
"Alexa Grasso":"亚历克莎·格拉索",
"Valentina Shevchenko":"瓦莲京娜·舍甫琴科",
"Erin Blanchfield":"艾琳布兰奇菲尔德",
"Manon Fiorot":"玛侬菲奥罗",
"Taila Santos":"泰拉桑托斯",
"Mackenzie Dern":"麦肯齐邓恩",
"Tecia Torres":"特西亚托雷斯",
"Luana Pinheiro":"卢安娜·皮涅罗",
"Tabatha Ricci":"塔巴莎·里奇",
"VivianeAraújo":"薇薇安·阿劳若",
"Ketlen Vieira":"凯特伦维埃拉",
"Pannie Kianzad":"潘妮·基安扎德",
"Mayra Bueno Silva":"梅拉·布埃诺·席尔瓦",
"Miesha Tate":"米莎泰特",
"Josiane Nunes":"约西亚娜努内斯",
"Mariya Agapova":"玛丽亚·阿加波娃",
"Zarrukh Adashev":"扎鲁克·阿达舍夫",
"Marcello Aguiar":"马塞洛·阿吉亚尔",
"Ashiek Ajim":"阿希克·阿吉姆",
"Omari Akhmedov":"奥马里·艾哈迈多夫",
"Yoshihiro Akiyama":"秋山义博",
"Alatengheili":"阿拉腾赫利",
"Herdem Alacabek":"赫德姆·阿拉卡贝克",
"Ali al-Qaisi":"阿里·盖西",
"Ildemar Alcantara":"伊尔德玛阿尔坎塔拉",
"Iuri Alcantara":"尤里·阿尔坎塔拉",
"Irina Alekseeva":"伊琳娜·阿列克谢娃",
"Ikram Aliskerov":"伊克拉姆·阿里斯克罗夫",
"Nurullo Aleie":"努鲁洛阿莱耶",
"Amir Aliakbari":"阿米尔阿里克巴里",
"Estefani Almeida":"埃斯特法尼·阿尔梅达",
"Ericka Almeida":"埃里卡·阿尔梅达",
"Jaime Alvarez":"海梅阿尔瓦雷斯",
"Amilcar Alves":"阿米尔卡·阿尔维斯",
"Thiago Alves":"蒂亚戈·阿尔维斯",
"Rayanne Amanda":"雷安阿曼达",
"Adlan Amagov":"阿德兰·阿马戈夫",
"Eryk Anders":"埃里克·安德斯",
"Alen Amedovski":"阿伦·阿梅多夫斯基",
"Tatsuya Ando":"安藤达也",
"Collin Anglin":"科林·安格林",
"Viscardi Andrade":"维斯卡迪·安德拉德",
"yoji anjo":"杨二安城",
"Josh Appelt":"乔什阿佩尔特",
"Shinsho Anzai":"新商安西",
"Zu Anyanwu":"祖安彦武",
"Gadzhimurad Antigulov":"加吉穆拉德·安提古洛夫",
"Aoriqileng":"奥日奇楞",
"Nina Nunes":"尼娜努内斯",
"Hashem Arkhagha":"哈希姆·阿卡哈",
"Akbarh Arreola":"阿克巴尔阿雷奥拉",
"Cesar Arzamendia":"塞萨尔·阿扎门迪亚",
"Askar Askarov":"阿斯卡·阿斯卡洛夫",
"Askar Askar":"阿斯卡 阿斯卡",
"Khusein Askhabov":"胡赛因·阿斯哈博夫",
"IBO ASLAN":"IBO阿斯兰",
"Leonardo Augusto Leleco":"莱昂纳多·奥古斯托·莱莱科",
"Olivier Aubin-Mercier":"奥利维尔·奥宾-麦西耶",
"Rich Attonito":"里奇·阿托尼托",
"Niklas Backstrom":"尼克拉斯·贝克斯特伦",
"Izabela Badurek":"伊莎贝拉·巴杜雷克",
"Seth Baczynski":"赛斯·巴钦斯基",
"Oluwale Bamgbose":"奥卢瓦勒竹糖",
"Mehdi Baghdad":"迈赫迪·巴格达",
"Shamar Bailey":"沙马尔·贝利",
"Siyar Bahadurzada":"西亚尔·巴哈杜尔扎达",
"Melsik Baghdasaryan":"梅尔西克·巴格达萨良",
"Humberto Bandenay":"温贝托·班德奈",
"Miguel Baeza":"米格尔·巴埃萨",
"Shonte Barnes":"肖特·巴恩斯",
"Renan Barao":"热南巴拉奥",
"Tae Hyun Bang":"泰贤方",
"Shayna Baszler":"莎娜巴斯勒",
"Javid Basharat":"贾维德·巴沙拉特",
"Rodolfo Bellato":"鲁道夫·贝拉托",
"Vitor Belfort":"维托·贝尔福特",
"Donavan Beard":"多纳万胡子",
"mirsad bektic":"米萨德贝克蒂奇",
"Deanna Bennett":"迪安娜贝内特",
"Danilo Belluardo":"达尼洛·贝卢亚多",
"Dieusel Berto":"迪厄塞尔贝托",
"Khadzhimurat Bestaev":"哈吉穆拉特·贝斯塔耶夫",
"KB Bhullar":"KB布拉尔",
"xie bin":"谢斌",
"Caio Bittencourt":"卡约比当古",
"Amaury Bitetti":"阿莫里·比泰蒂",
"magomed bibulatov":"马戈梅德·比布拉托夫",
"da'mon blackshear":"达蒙黑剪",
"Maximo Blanco":"马克西莫布兰科",
"Sherrard Blackledge":"谢拉德布莱克利奇",
"Tereza Bleda":"特蕾莎布莱达",
"galore bofando":"丰盛的博凡多",
"Dashawn Boatwright":"达肖恩·博特赖特",
"Ismael Bonfim":"伊斯梅尔邦芬",
"Caio Borralho":"卡约博拉略",
"Zach Borrego":"扎克博雷戈",
"Poliana Botelho":"波利亚娜博特略",
"Viacheslav Borshchev":"维亚切斯拉夫·博尔谢夫",
"Anvar Boynazarov":"安瓦尔博伊纳扎罗夫",
"Ebenezer Braga":"埃比尼泽布拉加",
"Joanderson Brito":"乔安德森布里托",
"Jarred Brooks":"震惊的布鲁克斯",
"Humberto Brown":"温贝托·布朗",
"Junie Browning":"朱妮布朗宁",
"Wuliji Buren":"五里鸡布人",
"Mikey Burnett":"米奇伯内特",
"Shane Burgos":"肖恩布尔戈斯",
"Paul Buentello":"保罗布恩泰罗",
"Modestas Bukauskas":"莫德斯塔斯·布考斯卡斯",
"Dennis Buzukja":"丹尼斯·布祖贾",
"Murilo Bustamante":"穆里洛布斯塔曼特",
"Nah-Shon Burrell":"伯勒尔；布瑞尔",
"YAN CABRAR":"颜卡布拉",
"Brian Camozzi":"布赖恩·卡莫兹",
"Priscila Cachoeira":"普里西拉·卡舒埃拉",
"Chico Camus":"奇科·加缪",
"Aleksa Camur":"阿列克萨卡穆尔",
"Shane Campbell":"肖恩·坎贝尔",
"Ariane Carnelossi":"阿丽亚娜卡内洛西",
"Liz Carmouche":"利兹卡尔穆什",
"Shonie Carter":"肖尼卡特",
"Spike Carlyle":"斯派克卡莱尔",
"Cortney Casey":"科特尼·凯西",
"Shane Carwin":"肖恩卡文",
"Antonio Carvalho":"安东尼奥·卡瓦略",
"Vinicius Cenci":"维尼修斯·先奇",
"Yosdenis Cedeno":"约斯丹尼斯·塞德诺",
"Gabriel Checco":"加布里埃尔切科",
"Ansar Chalangov":"安萨尔查兰戈夫",
"Sako Chivitchian":"萨科奇维奇安",
"Seungguk Choi":"崔胜国",
"Dooho Choi":"崔斗虎",
"Seungwoo Choi":"崔承佑",
"Ryo Chonan":"长南亮",
"Mike Ciesnolevicz":"迈克·西斯诺列维奇",
"Yui Chul Nam":"衣哲南",
"Misha Cirkunov":"米莎·切尔库诺夫",
"Laverne Clark":"拉文·克拉克",
"Felipe Colares":"费利佩·科拉雷斯",
"Rich Clementi":"富金文泰",
"Carlos Condit":"卡洛斯康迪特",
"Wes Combs":"韦斯库姆斯",
"Marcos Conrado Junior":"马科斯康拉多少年",
"Akira Corassani":"阿基拉科拉萨尼",
"Waldo Cortes Acosta":"沃尔多科尔特斯阿科斯塔",
"Orion Cosce":"猎户座科斯",
"J.C. Cottrell":"J.C.科特雷尔",
"JR Coughran":"小考夫兰",
"Ryan Couture":"瑞安寇图尔",
"Randy Couture":"兰迪寇图尔",
"Alberto Crane":"阿尔贝托起重机",
"Duane Crespo":"杜安·克雷斯波",
"Edilberto Crocota":"埃迪尔贝托·克罗科塔",
"Tim Credeur":"蒂姆·克雷德尔",
"Daron Cruickshank":"达伦·克鲁克香克",
"Jay Cucciniello":"杰·库奇尼罗",
"Emilio Cuellar":"埃米利奥奎利亚尔",
"Gleidson Cutis":"格莱森皮肤",
"Santo Curatolo":"圣库拉托洛",
"Henrique da Silva":"恩里克·达席尔瓦",
"Dayana DA Silva Santos":"达亚娜达席尔瓦桑托斯",
"Henrique da Silva Lopes":"恩里克·达席尔瓦·洛佩斯",
"Batgerel Danaa":"巴特格尔·丹拿",
"Mac Danzig":"麦克丹泽",
"Jarjis Danho":"贾吉斯·丹霍",
"Yorgan de Castro":"约根德卡斯特罗",
"Mike de la Torre":"迈克德拉托雷",
"Germaine de Randamie":"杰曼·德·兰达米",
"Shane del Rosario":"谢恩德尔罗萨里奥",
"Micol di Segni":"米科尔迪塞尼",
"Alessio di Chirico":"阿莱西奥·迪基里科",
"Vanessa DeMopoulos":"凡妮莎·德莫普洛斯",
"Marc Diakiese":"马克·迪亚基斯",
"TJ Dillashaw":"TJ迪拉肖",
"Hacran Dias":"哈克兰迪亚斯",
"Eldo Xavier Dias":"埃尔多泽维尔迪亚斯",
"Ozzy Diaz":"奥兹迪亚兹",
"Rico Disciullo":"里科迪斯库洛",
"AJ Dobson":"AJ多布森",
"Shana Dobson":"夏娜多布森",
"CB Dollaway":"CB多拉维",
"Geronimo Dos Santos":"杰罗尼莫·多斯桑托斯",
"acacio dos santos":"桑托斯相思树",
"Antonio Dos Santos":"安东尼奥多斯桑托斯",
"maiara amajanas dos santos":"马亚拉·阿马贾纳斯·多斯桑托斯",
"Elizeu dos santos":"埃利泽乌多斯桑托斯",
"Oleksandr doskalchuk":"亚历山大·多斯卡尔丘克",
"Tomasz Drwal":"托马斯·德瓦尔",
"Alexis Dufresne":"亚历克西斯杜弗雷纳",
"Milana Dudieva":"米兰娜·杜迪耶娃",
"Viktoriia Dudakova":"维多利亚·杜达科娃",
"Rolando Dy":"罗兰迪",
"Adli Edwards":"阿德里·爱德华兹",
"John-Olav Einemo":"约翰-奥拉夫·埃内莫",
"Per Eklund":"佩尔埃克伦德",
"Ramazan Emeev":"拉马赞埃米耶夫",
"Joao Elias":"若昂埃利亚斯",
"Sovannahry em":"万年历",
"Kolton Englund":"科尔顿英格兰",
"Jamall Emmers":"贾马尔埃默斯",
"Konstantin Erokhin":"康斯坦丁·埃罗欣",
"Efrain Escudero":"埃夫拉因·埃斯库德罗",
"Shaun Etchell":"肖恩埃切尔",
"Sijara Eubanks":"西贾拉·尤班克斯",
"Ashlee Evans-Smith":"阿什莉·埃文斯-史密斯",
"Tonya Evinger":"托尼亚·埃文格",
"MelindaFábián":"梅琳达法比安",
"Rinat Fakhretdinov":"里纳特·法赫雷迪诺夫",
"Zarah Fairn":"扎拉·费尔恩",
"Bartosz Fabinski":"巴尔托斯·法宾斯基",
"Wagnney Fabiano":"瓦格尼·法比亚诺",
"Urijah Faber":"乌利亚法伯",
"Maiquel Falcao":"迈克尔·法尔考",
"Rico Farrington":"里科·法林顿",
"CJ Fernandes":"CJ费尔南德斯",
"Bibiano Fernandes":"比比亚诺·费尔南德斯",
"CEZAR FERREIRA":"塞萨尔·费雷拉",
"Luigi Fioravanti":"路易吉菲奥拉万蒂",
"Edwin Figueroa":"埃德温菲格罗亚",
"Michal Figlak":"迈克尔菲格拉克",
"ISI FITIKEFU":"伊西·菲提克富",
"Ty Flores":"泰弗洛雷斯",
"AJ Fletcher":"AJ弗莱彻",
"Caros Fodor":"卡洛斯·福多",
"Jussier Formiga":"朱西尔福米加",
"Xavier Foupa-Pokam":"泽维尔·福帕-波卡姆",
"Brianna Fortino":"布里安娜福蒂诺",
"Artem Frolov":"阿尔乔姆弗罗洛夫",
"Donavon Frelow":"多纳文弗洛",
"Jinh Yu Frey":"Jinh Yu Frey",
"Zane Frazier":"赞恩弗雷泽",
"Masio Fullen":"马西奥富伦",
"Riki Fukuda":"福田力辉",
"Waylon Frost":"韦伦弗罗斯特",
"Ariel Gandulla":"阿里尔·甘杜拉",
"Shamil Gamzatov":"沙米尔·加姆扎托夫",
"Brian Gassaway":"布赖恩加萨维",
"Azamat Gashimov":"阿扎马特·加西莫夫",
"Pablo Garza":"巴勃罗加萨",
"darrel gholar":"达雷尔戈拉尔",
"Tiki Ghosn":"蒂基·戈恩",
"Manuel Gaxhja":"曼努埃尔·加夏",
"Karine Gevorgyan":"卡琳·格沃吉安",
"Brian Geraghty":"布赖恩杰拉蒂",
"Sergio Giglio":"塞尔吉奥吉廖",
"Micheal Gillmore":"迈克尔·吉尔摩",
"Amiran Gogoladze":"阿米兰·戈戈拉兹",
"Loopy Godinez":"疯疯癫癫的戈迪内斯",
"Akihiro Gono":"后野明博",
"Takanori Gomi":"五味隆则",
"Mikey Gonzalez":"米奇·冈萨雷斯",
"Jared Gooden":"贾里德·古登",
"themba gorimbo":"金银花",
"Thibault Gouti":"蒂博·古蒂",
"Tebaris Gordon":"特巴里斯·戈登",
"Renzo Gracie":"伦佐格雷西",
"TJ Grant":"TJ格兰特",
"Desmond Green":"德斯蒙德格林",
"Marcelo Guimaraes":"马塞洛·吉马良斯",
"Horacio Gutierrez":"奥拉西奥·古铁雷斯",
"Yazan Hajeh":"亚赞哈吉",
"Uriah Hall":"乌利亚大厅",
"Piotr Hallmann":"彼得·哈尔曼",
"Seohee Ham":"瑞熙火腿",
"Janay Harding":"珍妮·哈丁",
"Nasrat Haqparast":"纳斯拉特哈格帕拉斯特",
"Noe Hernandez":"诺埃尔南德斯",
"Nohelin Hernandez":"诺赫林埃尔南德斯",
"Richie Hightower":"里奇·海托华",
"Mizuto Hirota":"广田水人",
"hatsu hioki":"初日置",
"Kuniyoshi Hironaka":"弘中邦佳",
"Barb Honchak":"倒钩洪恰克",
"Yoshinori Horie":"堀江义典",
"Moti Horenstein":"莫蒂霍伦斯坦",
"Satoshi Honma":"本间聪",
"Kyoji Horiguchi":"堀口恭司",
"Saeed Hosseini":"赛义德侯赛尼",
"Shane Howell":"肖恩豪厄尔",
"Jamey-Lyn Horth":"杰米-林霍思",
"Minoki Ichihara":"市原美乃树",
"Valeri Ignatov":"瓦列里·伊格纳托夫",
"Fabiano Iha":"法比亚诺伊哈",
"Al Iaquinta":"亚昆塔",
"Khadis Ibragimov":"卡迪斯·易卜拉欣莫夫",
"guto incente":"古托因森特",
"Alvaro Ivan Lopez Rodrigues":"阿尔瓦罗·伊万·洛佩兹·罗德里格斯",
"Leandro Issa":"莱安德罗·伊萨",
"Teruto Ishihara":"石原照人",
"Naoki inoue":"井上直树",
"Wallid Ismail":"瓦利德·伊斯梅尔",
"Mizuki inoue":"井上美月",
"Enson Inoue":"井上恩森",
"Yoislandy Izquierdo":"伊斯基耶多岛",
"Yazmin Jauregui":"亚兹明·豪雷吉",
"Chanmi Jeon":"全灿美",
"Sung bin jo":"成斌祖",
"Asikerbai Jinensibieke":"阿斯克尔拜金恩斯别克",
"Asikeerbai Jinensibieke":"阿斯科尔白金恩斯别克",
"Kajan Johnson":"卡扬约翰逊",
"Liana Jojua":"藤本植物乔华",
"Krzysztof Jotko":"克日什托夫·约特科",
"Jocelyn Jones-Lybarger":"乔斯林·琼斯-莱巴格",
"Silvana Gomez Juarez":"西尔瓦娜·戈麦斯·华雷斯",
"Anshul Jubli":"安舒尔朱布里",
"lu kai":"吕凯",
"Oron Kahlon":"奥伦卡隆",
"Masanori Kanehara":"金原正典",
"Alex Karalexis":"亚历克斯·卡拉莱克西斯",
"Bharat Kandare":"巴拉特坎达雷",
"Sirwan Kakai":"西尔万加凯",
"Saidyokub Kakhramonov":"赛尤库布•卡赫拉莫诺夫",
"Kai Kamaka":"凯·卡马卡",
"Kyung Ho Kang":"姜庆浩",
"Impa Kasanganay":"因帕卡桑加奈",
"kasuya Yusuke":"霞屋佑介",
"Tatsuya Kawajiri":"川尻达也",
"Toshiomi Kazama":"风间敏臣",
"C.J. Keith":"C.J.基思",
"Aliaskhab Khizriev":"阿利亚斯哈布·希兹里耶夫",
"Wonbin Ki":"奇元彬",
"Maimaituoheti Keremuaili":"麦麦托赫提·科热麦埃里",
"Sergey Khandozhko":"谢尔盖·康多日科",
"Sinae Kikuta":"菊田真苗",
"Minwoo Kim":"金珉宇",
"Hanseul Kim":"金韩瑟",
"Katsunori Kikuno":"菊野克典",
"Ji Yeon Kim":"金智妍",
"Yusaku Kinoshita":"木下佑作",
"Koji Kitao":"北尾浩司",
"Kamuela Kirk":"卡姆埃拉柯克",
"Drakkar Klose":"德拉卡克洛泽",
"Felix Klinkhammer":"菲利克斯·克林克哈默",
"Kaloyan Kolev":"卡洛扬科列夫",
"Yuki Kondo":"近藤由纪",
"Syuri Kondo":"近藤秀里",
"Cheick Kongo":"切克刚果",
"Naoyuki Kotani":"小谷尚之",
"Jorgen Kruth":"约根克鲁斯",
"Karolina Kowalkiewicz":"卡罗琳娜·科瓦尔凯维奇",
"Tsuyoshi Kosaka":"小坂刚",
"Korey Kuppe":"科里·库佩",
"Mariusz Ksiazkiewicz":"马里乌什·克夏兹凯维奇",
"Rizvan Kuniev":"里兹万库涅夫",
"Aleksei Kunchenko":"阿列克谢昆琴科",
"Ramazan Kuramagomedov":"斋月库拉马戈梅多夫",
"Keigo Kunihara":"国原圭吾",
"Kiichi Kunimoto":"国本喜一",
"Luan Lacerda":"卢安·拉塞尔达",
"Yohan Lainesse":"约翰莱内斯",
"Noad Lahat":"诺德·拉哈特",
"Ryan Laflare":"瑞安·拉弗莱尔",
"Kwan Ho Kwak":"关浩国",
"TJ Laramie":"TJ拉勒米",
"Icho Larenas":"伊丘拉雷纳斯",
"Sione Latu":"西翁拉图",
"ilir latifi":"伊利尔·拉蒂菲",
"thanh le":"丹勒",
"Mickael Lebout":"迈克尔勒布特",
"Cung le":"康李",
"Mounir Lazzez":"穆尼尔·拉泽兹",
"Zviad Lazishvili":"兹维亚德·拉齐什维利",
"Cheyden Leialoha":"切登莱亚罗哈",
"Kimo Leopoldo":"基莫莱奥波尔多",
"Nik Lentz":"尼克伦茨",
"Alberto Cerro Leon":"阿尔贝托塞罗莱昂",
"Giacomo Lemos":"贾科莫莱莫斯",
"Thales Leites":"泰雷兹公司",
"Valerie Letourneau":"瓦莱丽·莱托诺",
"Marcus Levesseur":"马库斯·莱维塞尔",
"Rodrigo Lidio":"罗德里戈利迪奥",
"Zach Light":"扎克莱特",
"Dhiego Lima":"迭戈·利马",
"Hyun Gyu Lim":"贤圭林",
"Mabelly Lima":"玛贝利利马",
"Chi Lewis-Parry":"齐刘易斯招架",
"Lucio Linhares":"卢西奥·林哈雷斯",
"Tainara Lisboa":"泰娜拉·利斯波亚",
"Philipe Lins":"菲利普·林斯",
"Pingyuan Liu":"刘平原",
"Artem Lobov":"阿尔乔姆·洛博夫",
"Abner Lloveras":"阿布纳·洛维拉斯",
"Loma Lookboonmee":"洛玛-洛克布恩梅",
"dileno lopes":"迪莱诺洛佩斯",
"Brendan Loughnane":"布伦丹·洛南",
"Ange Loosa":"安吉鲁萨",
"Qiu Lun":"秋纶",
"Dalcha Lungiambula":"达尔查·伦亚布拉",
"Iasmin Lucindo":"亚斯敏卢辛多",
"Thaddeus Luster":"赛迪斯光泽",
"Waylon Lowe":"韦伦·劳",
"Pawan Maan":"帕万马安",
"Stevie Lynch":"史蒂夫·林奇",
"Caio Machado":"卡约·马查多",
"Valesca Machado":"瓦莱斯卡·马查多",
"Lyoto Machida":"町田良人",
"Reza Madadi":"礼萨马达迪",
"Caio Magalhaes":"卡约·马加良斯",
"Vinny Magalhaes":"文尼马加海斯",
"Abus Magomedov":"阿布斯·马戈梅多夫",
"Ruslan Magomedov":"鲁斯兰·马戈梅多夫",
"Rashid Magomedov":"拉希德·马戈梅多夫",
"Roshan Mainam":"肉山迈南",
"Levan Makashvili":"莱万马卡什维利",
"Zabit Magomedsharipov":"扎比特·马戈梅德沙里波夫",
"Nayara Maia":"纳亚拉玛亚",
"Troy Mandaloniz":"特洛伊·曼达洛尼兹",
"Nazareno Malegarie":"纳萨雷诺马莱加里",
"Bea Malecki":"比亚马莱茨基",
"Zach Makovsky":"扎克马可夫斯基",
"Jimi Manuwa":"吉米马努瓦",
"Danilo Marques":"达尼洛马克斯",
"Cesar Marscucci":"塞萨尔马尔库奇",
"Carmelo Marrero":"卡梅隆·马雷罗",
"Al Matavao":"阿尔马塔沃",
"Mike Massenzio":"迈克·马森齐奥",
"Mana Martinez":"法力马丁内斯",
"Michal Materla":"迈克尔·马特拉",
"Koyomi Matsushima":"松岛康代美",
"Vladimir Matyushenko":"弗拉基米尔·马秋申科",
"Francesco Maturi":"弗朗切斯科·马图里",
"Tateki Matsuda":"松田建树",
"Dotale Mayes":"多塔莱·梅耶斯",
"Sabina Mazo":"圆柏",
"Gan McGee":"甘麦基",
"Ryan McGilivray":"瑞安·麦克吉利夫雷",
"Conor McGregor":"康纳麦格雷戈",
"Garreth McLellan":"加雷斯·麦克莱伦",
"Yancy Medeiros":"扬西·梅代罗斯",
"Terrance McKinney":"特伦斯麦金尼",
"Rhys McKee":"里斯·麦基",
"Anistavio Medeiros":"阿尼斯塔维奥·梅代罗斯",
"Brian Melancon":"布赖恩梅兰松",
"UrošMedić":"乌罗斯梅迪奇",
"MateusMendonça":"马特乌斯门东萨",
"Alonzo Menifield":"阿朗佐梅尼菲尔德",
"Pietro Menga":"彼得罗门加",
"Bojan Mihajlovic":"博扬·米哈伊洛维奇",
"Yaotzin Meza":"耀津梅扎",
"Mo Miller":"莫米勒",
"Che Mills":"切米尔斯",
"Alberto Mina":"阿尔贝托·米纳",
"Ikuhisa Minowa":"三之轮育久",
"Kazuo Misaki":"美咲一夫",
"Mishima Dokonjonosuke":"三岛道康城之助",
"Vitor Miranda":"维托·米兰达",
"Eiji Mitsuoka":"光冈英二",
"Matt Mitrione":"马特·米特里奥内",
"Takeya Mizugaki":"水垣竹也",
"Roxanne Modafferi":"罗克珊·莫达菲里",
"Suman Mokhtarian":"苏曼·莫赫塔里安",
"Thiago Moises":"蒂亚戈莫伊塞斯",
"Ashkan Mokhtarian":"阿什坎·莫赫塔里安",
"Marlon Moraes":"马龙·莫赖斯",
"Sheymon Moraes":"谢蒙·莫拉斯",
"Vinicius Moreira":"维尼修斯·莫雷拉",
"Gegard Mousasi":"格加德·穆萨西",
"Kanako Murata":"村田加奈子",
"przemyslaw mysiala":"板栗",
"Magomed Mustafaev":"马戈梅德·穆斯塔法耶夫",
"kazuhiro nakamura":"中村和弘",
"Keita Nakamura":"中村启太",
"Rinya Nakamura":"中村凛也",
"Rin Nakai":"中井凛",
"Allan Nascimento":"艾伦·纳西门托",
"Rodrigo Nascimento":"罗德里戈·纳西门托",
"Stanislav Nedkov":"斯坦尼斯拉夫•内德科夫",
"Nair Melikyan":"奈尔梅利金",
"Nicolae negumereanu":"尼古拉·内古梅雷努",
"Reza Nazri":"礼萨纳兹里",
"Tafon Nchukwi":"塔方恩楚奎",
"Ismail Naurdiev":"伊斯梅尔·诺尔迪耶夫",
"Shane Nelson":"肖恩尼尔森",
"Bo Nickal":"博尼克尔",
"Jaimee Nievera":"杰米尼韦拉",
"Yamato Nishikawa":"西川大和",
"Minotauro Nogueira":"牛头怪诺盖拉",
"KJ NOONS":"K·J·诺斯",
"Phillipe Nover":"菲利普·诺维尔",
"Istela Nunes":"努内斯岛",
"Khabib Nurmagomedov":"哈比布·努尔马戈梅多夫",
"TJ O'Brien":"TJ奥布莱恩",
"koji oishi":"大石麴",
"JJ Okanovich":"JJ奥卡诺维奇",
"Yushin Okami":"大神友信",
"Aleksei Oleinik":"阿列克谢·奥莱尼克",
"Michal Oleksiejczuk":"迈克尔·奥列克谢祖克",
"Gadzhi Omargadzhiev":"加吉·奥马尔加吉耶夫",
"Chibwikem Onyenegecha":"切比维克 奥尼涅格查",
"Ode'Osbourne":"奥德奥斯本",
"Michihiro Omigawa":"小见川道博",
"Daniel Omielanczuk":"丹尼尔·奥米兰祖克",
"Alptekin Ozkilic":"阿普特金厄兹基利奇",
"Rachael Ostovich":"雷切尔·奥斯托维奇",
"Alistair Overeem":"阿利斯泰尔奥维瑞姆",
"Zak Ottow":"扎克奥托",
"Teemu Packalen":"提穆帕卡伦",
"Bart Palaszewski":"巴特·帕拉谢夫斯基",
"Sasha Palatnikov":"萨莎·帕拉特尼科夫",
"Rousimar Palhares":"鲁西马尔·帕哈雷斯",
"Soa Palelei":"索阿帕莱莱",
"Raulian Paiva":"劳莲派瓦",
"Jared Papazian":"贾里德帕帕齐安",
"Remco Pardoel":"雷姆科·帕多尔",
"Ramona Pascual":"雷蒙娜·帕斯夸尔",
"Jhonoven Pati":"乔诺文·帕蒂",
"Onassis Parungao":"奥纳西斯帕伦高",
"Zac Pauga":"扎克保加",
"Carlo Pedersoli":"卡洛佩德索利",
"Estevan Payan":"埃斯特万帕延",
"Pawel Pawlak":"帕维尔帕拉克",
"Sherman Pendergarst":"谢尔曼彭德加斯特",
"Cathal Pendred":"Cathal彭德雷德",
"Kurt Pellegrino":"库尔特佩莱格里诺",
"Viviane Pereira":"薇薇安·佩雷拉",
"Matějjpeňáz":"马捷伊佩纳兹",
"BJ Penn":"BJ佩恩",
"thiagoperpétuo":"蒂亚戈佩佩托",
"Hernani Perpetuo":"埃尔纳尼·佩佩托",
"Forrest Petz":"福雷斯特佩兹",
"Costas Philippou":"科斯塔斯·菲利普",
"Vinc Pichel":"文克·皮歇尔",
"Joao Pierini":"若昂·皮耶里尼",
"Oskar Piechota":"奥斯卡·皮埃乔塔",
"Dmitry Poberezhets":"德米特里·波贝雷泽茨",
"Gaetano Pirrello":"加埃塔诺·皮雷洛",
"Jamal Pogues":"贾马尔波格斯",
"Maki Pitolo":"真基皮托洛",
"Grigory Popov":"格里戈里·波波夫",
"Ruan Potts":"阮波茨",
"ihor Potieria":"伊霍尔·波蒂利亚",
"Kyle Prepolec":"凯尔·普雷波莱克",
"Michel Prazeres":"米歇尔·普拉泽雷斯",
"Carlo Prater":"卡洛普拉特",
"Shane Primm":"肖恩普里姆",
"Claudio Puelles":"克劳迪奥·普埃勒斯",
"Lara Procopio":"劳拉·普罗科皮奥",
"Isaih Quinones":"以赛亚奎诺斯",
"Vinicius Queiroz":"维尼修斯·奎罗斯",
"Benji Radach":"本吉·拉达奇",
"Jose Quinonez":"何塞·奎诺内斯",
"Loik Radzhabov":"洛伊克·拉扎博夫",
"Bec Rawlings":"贝克·罗林斯",
"Mitch Raposo":"米奇拉波索",
"Stevie Ray":"史蒂夫·雷",
"Mateuszrębecki":"马特乌斯雷贝茨基",
"Paulo Renato Jr.":"小保罗·雷纳托",
"Leigh Remedios":"雷梅黛丝",
"Marco Polo Reyes":"马可波罗雷耶斯",
"Esteban Ribovics":"埃斯特万·里博维奇",
"Theo Rlayang":"拉扬",
"Vagner Rocha":"瓦格纳·罗查",
"Carlos Eduardo Rocha":"卡洛斯·爱德华多·罗沙",
"Shane Roller":"谢恩·罗尔",
"Max Rohskopf":"马克斯·罗斯科普夫",
"Juancamilo Ronderos":"胡安卡米洛·朗德罗斯",
"Zhu":"朱",
"Mara Romero Borella":"马拉·罗梅罗·博雷拉",
"Yoel Romero":"尤尔·罗梅罗",
"Joao Roque":"若昂洛克",
"Hilarie Rose":"希拉莉·罗斯",
"Jared Rosholt":"贾里德·罗肖特",
"Rodrigo Ruas":"罗德里戈鲁斯",
"Rodolfo Rubio":"鲁道夫卢比奥",
"Marco Ruas":"马可鲁斯",
"Gabe Ruediger":"加布鲁迪格",
"Tarec Saffiedine":"塔雷克萨菲丁",
"Bas Rutten":"下吕腾",
"Gokhan Saki":"悟饭咲",
"Saparbeg Safarov":"萨帕尔贝格萨法罗夫",
"Alessio Sakara":"阿莱西奥萨卡拉",
"Ovince Saint Preus":"文斯圣普鲁斯",
"Kazushi Sakuraba":"樱庭一士",
"Hayato Sakurai":"樱井隼人",
"Joby Sanchez":"乔比·桑切斯",
"Hector Sandoval":"赫克托·桑多瓦尔",
"Shaheen Santana":"沙欣桑塔纳",
"Roldan Sangcha-an":"罗丹·桑查安",
"Thiago Santos":"蒂亚戈桑托斯",
"Marilia Santos":"玛丽莉亚·桑托斯",
"Edivan Santos":"埃迪万·桑托斯",
"Iliarde Santos":"伊利亚德桑托斯",
"Keisuke Sasu":"佐须圭佑",
"Yuki Sasaki":"佐佐木由纪",
"Takeori Sato":"佐藤武织",
"Matheus Scheffel":"马修斯·谢菲尔",
"Jeka Saragih":"杰卡萨拉吉",
"Samy Schiavo":"萨米夏沃",
"Fabiano Scherner":"法比亚诺舍纳",
"Darrill Schoonover":"达里尔斯库诺弗",
"Alex Schoenauer":"亚历克斯舍纳尔",
"Semmy Schilt":"塞米席尔特",
"Yedam Seo":"艺谈徐",
"Matthew Semelsberger":"马修·塞默斯伯格",
"Tetsuya Seki":"关哲哉",
"Stefan Sekulic":"斯特凡塞库利奇",
"Liliya Shakirova":"莉莉娅·夏奇罗娃",
"Edmen Shahbazyan":"埃德曼·沙巴赞",
"Rosi Sexton":"罗西塞克斯顿",
"Leon Shahbazyan":"莱昂·沙巴赞",
"Kamal Shalorus":"卡马尔·沙洛鲁斯",
"Fredy Serrano":"弗雷迪塞拉诺",
"Shunichi Shimizu":"清水俊一",
"Henrique Shiguemoto":"恩里克志格本",
"Antonina Shevchenko":"安东尼娜·舍甫琴科",
"Jansey Silva":"詹西·席尔瓦",
"Liudvik Sholinian":"柳德维克·肖利尼安",
"Sam Sicilia":"山姆·西西利亚",
"Leandro Silva":"莱安德罗·席尔瓦",
"Joaquim Silva":"若阿金·席尔瓦",
"Assuerio Silva":"阿苏里奥·席尔瓦",
"Jamey Simmons":"杰米·西蒙斯",
"Elias Silverio":"埃利亚斯西尔维里奥",
"Wes Sims":"西姆斯",
"Chas Skelly":"查斯凯利",
"Gian Siqueira":"吉安西奎拉",
"lodune sincaid":"洛登辛凯德",
"Mitchell Sipe":"米切尔刀槽花纹",
"Arjan Singh Bhullar":"阿尔琼·布拉",
"Rameau Sokoudjou":"拉莫·索库朱",
"dmitrii smoliakov":"德米特里·斯莫利亚科夫",
"Renato Sobral":"雷纳托·索布拉尔",
"Shimon Smotritsky":"西蒙·斯莫特里茨基",
"Chael Sonnen":"查尔索南",
"Krzysztof Soszynski":"克日什托夫·索申斯基",
"Emiliano Sordi":"埃米利亚诺索尔迪",
"Dmitry Sosnovskiy":"德米特里·索斯诺夫斯基",
"Punahele Soriano":"普纳赫莱索里亚诺",
"Livinha Souza":"利维尼亚苏萨",
"Bruno Souza":"布鲁诺苏萨",
"Andreas Spang":"安德烈亚斯斯邦",
"Dmitrei Stepanov":"德米特雷·斯捷潘诺夫",
"Dustin Stoltzfus":"达斯汀斯托尔兹弗斯",
"Niklas Stolze":"尼克拉斯斯托尔兹",
"Julija Stoliarenko":"朱莉娅·斯托利亚连科",
"Lazar Stojadinovic":"拉扎尔·斯托贾迪诺维奇",
"Dan Stittgen":"丹·斯蒂根",
"Denis Stojnic":"丹尼斯·斯托伊尼克",
"Darko Stosic":"达尔科·斯托西奇",
"Sam Stout":"山姆斯托特",
"Stefan Struve":"斯特凡·司徒卢威",
"Genki Sudo":"须藤元气",
"Lukasz Sudolski":"卢卡斯·苏多尔斯基",
"Mike Stumpf":"迈克·斯坦普夫",
"Danilo Suzart":"达尼洛·苏扎特",
"Eugenio Tadeu":"尤金尼奥·塔德乌",
"Oumar Sy":"欧玛施",
"Issei Tamura":"田村一诚",
"Oleg Taktarov":"奥列格·塔克塔罗夫",
"Akitoshi Tamura":"田村明俊",
"daiju takase":"大树高濑",
"Tatsuro Taira":"平达郎",
"Mairbek Taisumov":"迈尔贝克·泰苏莫夫",
"Thiago Tavares":"蒂亚戈·塔瓦雷斯",
"Glover Teixeira":"格洛弗·特谢拉",
"Tra Telligman":"特里格曼",
"Taneisha Tennant":"种内沙坦南特",
"Motonobu Tezuka":"手冢治虫",
"Paulo Thiago":"保罗蒂亚戈",
"Elias Theodorou":"埃利亚斯·西奥多罗",
"Din Thomas":"丁托马斯",
"Tuco Tokkos":"图科托科斯",
"DuškoTodorović":"杜斯科托多罗维奇",
"Denis Tiuliulin":"丹尼斯·图柳林",
"Simeon Thoresen":"西蒙·托雷森",
"Desmond Torres":"德斯蒙德·托雷斯",
"Miguel Angel Torres":"米格尔·安吉尔·托雷斯",
"Salim Touahri":"萨利姆·图阿里",
"Dequan Townsend":"德全汤森",
"tiago trator":"蒂亚戈特拉",
"Tor Troeng":"托特龙",
"Teila Tuli":"泰拉图利",
"Zubaira Tukhugov":"祖拜拉·图胡戈夫",
"Jumabieke Tuerxun":"朱玛别克图尔逊",
"Rei Tsuruya":"鹤屋玲",
"Gasan Umalatov":"加桑·乌马拉托夫",
"Takeru Uchida":"内田健",
"Sho Patrick Usami":"翔帕特里克宇佐美",
"Hector Urbina":"赫克托乌尔维纳",
"Yasuhiro Urushitani":"漆谷泰博",
"Caol Uno":"宇野薫",
"Elias Urbina":"埃利亚斯乌尔维纳",
"Darren Uyenoyama":"达伦上野山",
"Genaro Valdez":"杰纳罗瓦尔迪兹",
"Richie Vaculik":"里奇瓦库利克",
"Kazula Vargas":"卡祖拉巴尔加斯",
"Guilherme Vasconcelos":"吉列尔梅·瓦斯孔塞洛斯",
"Paige Vanzant":"佩奇范赞特",
"Jared Vanderaa":"贾里德·范德拉",
"Luigi Vendramini":"路易吉文德拉米尼",
"Bojan Velickovic":"博扬维利科维奇",
"Polyana Viana":"波利亚纳维亚纳",
"Renato Verissimo":"雷纳托·维里西莫",
"tamires vidal":"塔米雷斯比达尔",
"Nikolay Veretennikov":"尼古拉·韦列捷尼科夫",
"Ernie Verdicia":"厄尼·维迪西亚",
"Reginaldo Vieira":"雷吉纳尔多维埃拉",
"Rodolfo Vieira":"鲁道夫维埃拉",
"Danillo Villefort":"达尼罗维尔福",
"Armando Villarreal":"阿曼多比利亚雷亚尔",
"Ike Villanueva":"艾克维拉纽瓦",
"Yuri Villefort":"尤里维尔福",
"Falaniko Vitale":"法拉尼科·维塔莱",
"Cheyanne Vlismas":"夏安·维利斯玛斯",
"TJ Waldburger":"TJ沃尔德伯格",
"Crafton Wallace":"克拉夫顿华莱士",
"Terrion Ware":"特里昂·瓦雷",
"Royston Wee":"罗伊斯顿威",
"Fabricio Werdum":"法布里西奥·温杜姆",
"Garett Whiteley":"加雷特怀特利",
"Sheldon Westcott":"谢尔顿韦斯科特",
"Khaos Williams":"考斯·威廉姆斯",
"Keith Wisniewski":"基思维斯涅夫斯基",
"Marcin Wrzosek":"马尔钦·沃佐塞克",
"Keichiro Yamamiya":"山宫启一郎",
"Yamamoto Norifumi":"山本纪文",
"Yamamoto Kenichi":"山本健一",
"Rani Yahya":"拉尼叶海亚",
"Qihui Yan":"闫启辉",
"Sang Hoon Yoo":"孙昊永",
"Masutatsu Yano":"矢野增达",
"Cale Yarbrough":"卡尔亚伯勒",
"hu yaozong":"胡耀宗",
"Emmanuel Yarbrough":"伊曼纽尔·亚伯勒",
"Shanna Young":"莎娜年轻",
"Shane Young":"肖恩杨",
"Zach Zane":"扎克赞恩",
"Youssef Zalal":"优素福扎拉尔",
"Joao Zaiden":"若昂再传",
"besam yousef":"比萨姆优素福",
"Yao Zhikui":"姚志奎",
"LV Zhenhong":"吕振红",
"FarèsZiam":"法雷兹亚姆",
"Zhalgas Zhumagulov":"扎尔加斯朱马古洛夫",
"Yi Zha":"益扎",
"Tiequan Zhang":"张铁拳"}

for key in translate_total.keys():
    if translate_total[key] in not_tr.keys():
        value=not_tr[translate_total[key]]
        translate_total[key]=value




    


# need_repair={
#     "Aljamain Sterling":"阿尔贾曼·斯特林",
#     "Max Holloway":"马克斯·霍洛威"
# }

# weight = {
#     "Flyweight": "蝇量级",
#     "Bantamweight": "雏量级",
#     "Featherweight": "羽量级",
#     "Lightweight": "轻量级",
#     "Welterweight": "次中量级",
#     "Middleweight": "中量级",
#     "Light Heavyweight": "轻重量级",
#     "Heavyweight": "重量级",
#     "Women's Strawweight": "女子草量级",
#     "Women's Flyweight": "女子蝇量级",
#     "Women's Bantamweight": "女子雏量级",
#     "Women's Featherweight": "女子羽量级",
# }
# weight_division = {k+" Division": weight[k]+"部门" for k in weight.keys()}
# weight_boot = {k+" Bout": weight[k]+"比赛" for k in weight.keys()}
# weight_boot_title = {k+" Title Bout": weight[k]+"冠军争夺赛" for k in weight.keys()}
# need_repair.update(weight_division)
# need_repair.update(weight_boot)
# need_repair.update(weight_boot_title)

# for key in need_repair.keys():
#     hash_key=hashlib.sha1(key.encode('"utf-8', 'strict')).hexdigest()
#     translate_total[hash_key]=need_repair[key]
#     # if hash_key in translate_total:
#     #     translate_total[hash_key]=need_repair[key]
#     #     print(translate_total[hash_key])
# #print(json.dumps(translate_total))
with open(translate_file_path, "w", encoding='utf-8') as file:
    file.write(str(json.dumps(translate_total)))

# from googletrans import Translator

# translator = Translator(service_urls=['translate.google.com','translate.google.co.kr'])
# tr_result=translator.translate("你好", "zh-CN", "en")
# print(tr_result)